CREATE TABLE Users (
    ID SERIAL PRIMARY KEY,
    Name TEXT,
    Email TEXT UNIQUE,
    Dob DATE
);

ALTER SEQUENCE Users_ID_seq RESTART WITH 1;

CREATE TABLE Account (
    Username TEXT PRIMARY KEY,
    Password TEXT NOT NULL,
    Role TEXT NOT NULL,
    UserID INT UNIQUE NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE
);

CREATE TABLE Test (
    ID SERIAL PRIMARY KEY,
    Title TEXT NOT NULL,
    Description TEXT,
    NumberQuestion INT,
    Passcode TEXT UNIQUE,
    TestTime INT NOT NULL,
    TimeOpen TIMESTAMP,
    TimeClose TIMESTAMP,
    TeacherID INT NOT NULL,
    FOREIGN KEY (TeacherID) REFERENCES Users(ID) ON DELETE CASCADE
);

ALTER SEQUENCE Test_ID_seq RESTART WITH 1;

CREATE TABLE Result (
    StudentID INT NOT NULL,
    TestID INT NOT NULL,
    TotalScore FLOAT,
    StartTime TIMESTAMP,
    EndTime TIMESTAMP,
    PRIMARY KEY (StudentID, TestID),
    FOREIGN KEY (StudentID) REFERENCES Users(ID) ON DELETE CASCADE,
    FOREIGN KEY (TestID) REFERENCES Test(ID) ON DELETE CASCADE
);

CREATE TABLE Question (
    ID SERIAL PRIMARY KEY,
    Content TEXT NOT NULL,
    Score FLOAT NOT NULL,
    TestID INT NOT NULL,
    FOREIGN KEY (TestID) REFERENCES Test(ID) ON DELETE CASCADE
);

ALTER SEQUENCE Question_ID_seq RESTART WITH 1;

CREATE TABLE StudentAnswer (
    StudentID INT NOT NULL,
    QuestionID INT NOT NULL,
    IsCorrect BOOLEAN NOT NULL DEFAULT FALSE,
    AnswerID INT DEFAULT NULL,
    PRIMARY KEY (StudentID, QuestionID),
    FOREIGN KEY (StudentID) REFERENCES Users(ID) ON DELETE CASCADE,
    FOREIGN KEY (QuestionID) REFERENCES Question(ID) ON DELETE CASCADE
);

CREATE TABLE Answer (
    ID SERIAL PRIMARY KEY,
    Content TEXT NOT NULL,
    IsCorrect BOOLEAN NOT NULL,
    QuestionID INT NOT NULL,
    FOREIGN KEY (QuestionID) REFERENCES Question(ID) ON DELETE CASCADE
);

ALTER SEQUENCE Answer_ID_seq RESTART WITH 1;